### ISSUE TITLE
Is there any web interactive program running without docker

### ISSUE THREAD

**Issue by 1390806607** [martindyrba/DeepLearningInteractiveVis#13]

**Comment by martindyrba** [comment]
Please checkout the git repository and install all dependencies in your Python environment.
Then you can change to the main folder including the InteractiveVis subfolder.
There you can run the command:
`bokeh serve InteractiveVis --show`
in order to locally start the Bokeh webserver and show the app in your browser. It should directly work like this.

Best regards,
Martin

**Comment by 1390806607** [comment]
Ok, thank you. I'll try
